// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    return $('.btnedit').click(function() {
      var that, todoid, url;
      that = this;
      todoid = $(this).data("todoid");
      url = Routing.generate("todo_update", {
        id: todoid
      });
      return $.ajax(url, {
        type: "POST",
        contentType: "application/json",
        success: function(data) {
          if (data.completed === 0) {
            $('.toggle').checked = null;
            return $(that).parents("li").removeClass("completed");
          } else {
            $('.toggle').checked = "yes";
            return $(that).parents("li").addClass("completed");
          }
        },
        error: function(xhr, ajaxOptions, thrownError) {
          alert(xhr.status);
          return alert(thrownError);
        }
      });
    });
  });

}).call(this);
