todo:
    pattern:  /
    defaults: { _controller: "BackendBundle:Todo:index" }

todo_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:Todo:create" }
    requirements: { _method: post }

todo_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendBundle:Todo:update" }
    requirements: { _method: post|put }
    options:
        expose: true

todo_delete:
    pattern:  /{id}/delete/{token}
    defaults: { _controller: "BackendBundle:Todo:delete" }
    requirements: { _method: post|delete }

todo_clearcompleted:
    pattern:  /clearcompleted
    defaults: { _controller: "BackendBundle:Todo:clearcompleted" }
    requirements: { _method: get }

todo_toggle:
    pattern:  /todotoggle
    defaults: { _controller: "BackendBundle:Todo:todotoggle" }
